# Main php tasks file
- name: Ubuntu tasks
  include_tasks: "ubuntu.yml"
  when: ansible_os_family == "Debian"

- name: Centos tasks
  include_tasks: "centos.yml"
  when: ansible_os_family == "RedHat"